# 啟動開發環境：
# docker compose -f docker-compose.yml up -d
# docker exec -it ai-verifying bash

# 停止開發環境：
# docker compose -f docker-compose.yml down

services:
  verifying-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-verifying
    volumes:
      # 掛載整個專案目錄，實現熱更新
      - .:/app
    working_dir: /app
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: npm run dev
